projects:
  granphql:
    schemaPath: src/mock/schema/schema.graphql
    extensions:
      endpoints:
        dev: http://115.159.154.194:8080/graphql
  json:
    schemaPath: src/mock/schema/schema.json
    extensions:
      endpoints:
        dev: http://115.159.154.194:8080/graphql
